apiVersion: v1
kind: Namespace
metadata:
  name: digital-cabin-job-scheduler-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-cabin-job-scheduler-api-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: digital-cabin-job-scheduler-api
  template:
    metadata:
      name: digital-cabin-job-scheduler-api
      labels:
        app: digital-cabin-job-scheduler-api
    spec:
      containers:
      - name: digital-cabin-job-scheduler-api
        image: openaiacr.azurecr.io/digital-cabin-job-scheduler-api:6666
        env:
        - name: REPOS_NAME
          value: digital-cabin-job-scheduler-api
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: digital-cabin-job-scheduler-api-service
spec:
  selector:
    app: digital-cabin-job-scheduler-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-cabin-job-scheduler-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /digital-cabin-job-scheduler-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: digital-cabin-job-scheduler-api-service
            port:
              number: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: digital-cabin-job-scheduler-api-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digital-cabin-job-scheduler-api-deployment
  targetCPUUtilizationPercentage: 80